# Project: Project1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o c_stack.o
LINKOBJ  = main.o c_stack.o
LIBS     = -L"D:/LeStoreDownload/Dev-Cpp/MinGW64/lib" -L"D:/LeStoreDownload/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"D:/LeStoreDownload/Dev-Cpp/MinGW64/include" -I"D:/LeStoreDownload/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/LeStoreDownload/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/LeStoreDownload/Dev-Cpp/MinGW64/include" -I"D:/LeStoreDownload/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/LeStoreDownload/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/LeStoreDownload/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Project1.exe
CXXFLAGS = $(CXXINCS) -ansi -g3
CFLAGS   = $(INCS) -ansi -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

c_stack.o: c_stack.cpp
	$(CPP) -c c_stack.cpp -o c_stack.o $(CXXFLAGS)
